"use client";
import { useState } from "react";
import { Heart } from "lucide-react";

/** Donation progress bar with accessible value semantics. */
export function DonationProgress({ value, goal }: { value: number; goal: number }) { const pct = goal > 0 ? Math.min(100, Math.round((value / goal) * 100)) : 0; return <div><div className="flex justify-between text-sm"><span>${value.toLocaleString()} raised</span><span>${goal.toLocaleString()} goal</span></div><div role="progressbar" aria-valuenow={pct} aria-valuemin={0} aria-valuemax={100} className="mt-2 h-3 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{ width: `${pct}%` }} /></div></div>; }
/** Calculates approximate impact from selected donation amount. */
export function ImpactCalculator({ amount, unitCost, label }: { amount: number; unitCost: number; label: string }) { const units = Math.max(0, Math.floor(amount / unitCost)); return <p className="rounded-lg bg-muted p-4 text-sm"><strong>{amount.toLocaleString("en", { style: "currency", currency: "USD" })}</strong> can fund approximately <strong>{units}</strong> {label}.</p>; }
/** Secure payment CTA button used at final donation review. */
export function PaymentCta({ amount, disabled }: { amount: number; disabled?: boolean }) { return <button disabled={disabled} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-md bg-primary px-6 font-semibold text-primary-foreground disabled:opacity-50"><Heart aria-hidden className="h-4 w-4" />Donate {amount.toLocaleString("en", { style: "currency", currency: "USD" })}</button>; }
/** Complete reusable donation widget with amount, frequency, impact, and submit CTA. */
export function DonationWidget({ amounts = [25, 50, 100, 250], unitCost = 25 }: { amounts?: number[]; unitCost?: number }) { const [amount, setAmount] = useState(amounts[1] ?? 50); const [frequency, setFrequency] = useState<"once" | "monthly">("monthly"); return <form className="rounded-xl border bg-surface p-6 shadow-card" aria-label="Donation form"><fieldset><legend className="font-semibold">Choose amount</legend><div className="mt-4 grid grid-cols-2 gap-3">{amounts.map((option) => <button key={option} type="button" aria-pressed={amount === option} onClick={() => setAmount(option)} className="min-h-12 rounded-md border bg-background px-4 font-semibold aria-pressed:bg-primary aria-pressed:text-primary-foreground">${option}</button>)}</div><label className="mt-4 block text-sm font-medium" htmlFor="custom-amount">Custom amount</label><input id="custom-amount" inputMode="numeric" min={1} value={amount} onChange={(event: any) => setAmount(Number(event.currentTarget.value))} className="mt-2 min-h-12 w-full rounded-md border bg-background px-4" /></fieldset><fieldset className="mt-6"><legend className="font-semibold">Frequency</legend><div className="mt-3 grid grid-cols-2 gap-3">{(["once", "monthly"] as const).map((option) => <button key={option} type="button" aria-pressed={frequency === option} onClick={() => setFrequency(option)} className="min-h-12 rounded-md border bg-background px-4 capitalize aria-pressed:bg-primary aria-pressed:text-primary-foreground">{option}</button>)}</div></fieldset><div className="mt-6"><ImpactCalculator amount={amount} unitCost={unitCost} label="care kits" /></div><p className="mt-4 text-sm text-foreground/60">Secure payment. Receipt delivered by email. Frequency: {frequency}.</p><div className="mt-6"><PaymentCta amount={amount} disabled={amount <= 0} /></div></form>; }
