import Link from "next/link";
import type { ReactNode } from "react";
import { ArrowRight, Box } from "lucide-react";
import { cn } from "@/utils/cn";

export type HeroAction = { label: string; href: string; variant?: "primary" | "secondary" };
function HeroActions({ actions }: { actions?: HeroAction[] }) { return actions?.length ? <div className="mt-8 flex flex-col gap-3 sm:flex-row">{actions.map((action) => <Link key={action.href} href={action.href} className={cn("inline-flex min-h-12 items-center justify-center rounded-md px-6 font-semibold", action.variant === "secondary" ? "border bg-surface" : "bg-primary text-primary-foreground")}>{action.label}<ArrowRight aria-hidden className="ml-2 h-4 w-4" /></Link>)}</div> : null; }
/** Premium editorial hero with accessible heading and action hierarchy. */
export function PremiumHero({ eyebrow, title, description, actions, aside }: { eyebrow?: string; title: string; description: string; actions?: HeroAction[]; aside?: ReactNode }) { return <section className="grid gap-10 py-16 md:py-24 lg:grid-cols-[1.1fr_.9fr] lg:items-center"> <div>{eyebrow ? <p className="text-sm font-semibold uppercase tracking-[.18em] text-foreground/60">{eyebrow}</p> : null}<h1 className="mt-4 font-display text-5xl font-semibold leading-[.95] tracking-[-.05em] md:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-foreground/72">{description}</p><HeroActions actions={actions} /></div>{aside ? <div>{aside}</div> : null}</section>; }
/** Video hero with transcript link and no autoplay audio by default. */
export function VideoHero({ title, description, poster, videoSrc, transcriptHref, actions }: { title: string; description: string; poster: string; videoSrc: string; transcriptHref: string; actions?: HeroAction[] }) { return <section className="py-16 md:py-24"><div className="overflow-hidden rounded-xl border bg-surface shadow-card"><video className="aspect-video w-full object-cover" controls preload="metadata" poster={poster}><source src={videoSrc} /></video><div className="p-6 md:p-8"><h1 className="font-display text-4xl font-semibold">{title}</h1><p className="mt-3 max-w-3xl text-foreground/70">{description}</p><a className="mt-4 inline-flex text-sm font-semibold underline" href={transcriptHref}>Read transcript</a><HeroActions actions={actions} /></div></div></section>; }
/** Lightweight 3D hero fallback container for progressive WebGL enhancement. */
export function ThreeDHeroPlaceholder({ title, description }: { title: string; description: string }) { return <section className="grid gap-8 rounded-xl border bg-gradient-to-br from-muted to-surface p-8 md:grid-cols-2 md:items-center"><div><h1 className="font-display text-5xl font-semibold">{title}</h1><p className="mt-4 text-foreground/70">{description}</p></div><div className="grid aspect-square place-items-center rounded-xl border bg-background/70"><Box aria-hidden className="h-16 w-16 text-foreground/45" /><span className="sr-only">Decorative 3D scene fallback</span></div></section>; }
/** Reusable CTA banner for conversion moments. */
export function CtaBanner({ title, description, action }: { title: string; description: string; action: HeroAction }) { return <aside className="rounded-xl border bg-primary p-8 text-primary-foreground md:flex md:items-center md:justify-between"><div><h2 className="font-display text-4xl font-semibold">{title}</h2><p className="mt-3 max-w-2xl text-primary-foreground/80">{description}</p></div><Link className="mt-6 inline-flex min-h-12 items-center rounded-md bg-background px-6 font-semibold text-foreground md:mt-0" href={action.href}>{action.label}</Link></aside>; }
