import { defineField, defineType } from "sanity";

const slugField = defineField({ name: "slug", type: "slug", options: { source: "title" }, validation: (rule) => rule.required() });
const imageField = defineField({ name: "image", type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", type: "string", validation: (rule) => rule.required() })] });
export const homepage = defineType({ name: "homepage", title: "Homepage", type: "document", fields: [defineField({ name: "title", type: "string", validation: (rule) => rule.required() }), defineField({ name: "seo", type: "seo" }), defineField({ name: "hero", type: "object", fields: [defineField({ name: "eyebrow", type: "string" }), defineField({ name: "title", type: "string", validation: (rule) => rule.required() }), defineField({ name: "description", type: "text", rows: 3 }), defineField({ name: "primaryCta", type: "link" }), defineField({ name: "secondaryCta", type: "link" }), defineField({ name: "dashboardMetric", type: "object", fields: [defineField({ name: "value", type: "number" }), defineField({ name: "label", type: "string" })] }), defineField({ name: "proofPoints", type: "array", of: [{ type: "string" }] }), imageField] }), defineField({ name: "trust", type: "object", fields: [defineField({ name: "eyebrow", type: "string" }), defineField({ name: "title", type: "string" }), defineField({ name: "description", type: "text" }), defineField({ name: "stats", type: "array", of: [{ type: "stat" }] }), defineField({ name: "highlights", type: "array", of: [{ type: "string" }] }), defineField({ name: "partners", type: "array", of: [{ type: "reference", to: [{ type: "partner" }] }] })] }), defineField({ name: "featuredPrograms", type: "array", of: [{ type: "reference", to: [{ type: "program" }] }] }), defineField({ name: "impactTimeline", type: "array", of: [{ type: "timelineItem" }] }), defineField({ name: "featuredStory", type: "reference", to: [{ type: "story" }] }), defineField({ name: "featuredNews", type: "reference", to: [{ type: "news" }] }), defineField({ name: "testimonials", type: "array", of: [{ type: "reference", to: [{ type: "testimonial" }] }] })] });
export const program = defineType({ name: "program", title: "Program", type: "document", fields: [defineField({ name: "title", type: "string", validation: (rule) => rule.required() }), slugField, defineField({ name: "summary", type: "text", rows: 3 }), defineField({ name: "progress", type: "number", validation: (rule) => rule.min(0).max(100) }), imageField, defineField({ name: "seo", type: "seo" })] });
export const project = defineType({ name: "project", title: "Project", type: "document", fields: [defineField({ name: "title", type: "string" }), slugField, defineField({ name: "program", type: "reference", to: [{ type: "program" }] }), defineField({ name: "location", type: "string" }), defineField({ name: "progress", type: "number" }), imageField, defineField({ name: "seo", type: "seo" })] });
export const story = defineType({ name: "story", title: "Story", type: "document", fields: [defineField({ name: "title", type: "string" }), slugField, defineField({ name: "excerpt", type: "text" }), defineField({ name: "quote", type: "text" }), imageField, defineField({ name: "seo", type: "seo" })] });
export const news = defineType({ name: "news", title: "News", type: "document", fields: [defineField({ name: "title", type: "string" }), slugField, defineField({ name: "description", type: "text" }), defineField({ name: "publishedAt", type: "datetime" }), imageField, defineField({ name: "seo", type: "seo" })] });
export const event = defineType({ name: "event", title: "Event", type: "document", fields: [defineField({ name: "title", type: "string" }), slugField, defineField({ name: "startsAt", type: "datetime" }), defineField({ name: "location", type: "string" }), defineField({ name: "description", type: "text" }), defineField({ name: "seo", type: "seo" })] });
export const person = defineType({ name: "person", title: "Team / Leadership", type: "document", fields: [defineField({ name: "name", type: "string" }), slugField, defineField({ name: "role", type: "string" }), defineField({ name: "group", type: "string", options: { list: ["team", "leadership"] } }), defineField({ name: "bio", type: "text" }), imageField] });
export const partner = defineType({ name: "partner", title: "Partner", type: "document", fields: [defineField({ name: "name", type: "string" }), slugField, defineField({ name: "url", type: "url" }), defineField({ name: "logo", type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", type: "string" })] })] });
export const testimonial = defineType({ name: "testimonial", title: "Testimonial", type: "document", fields: [defineField({ name: "quote", type: "text" }), defineField({ name: "name", type: "string" }), defineField({ name: "role", type: "string" })] });
export const report = defineType({ name: "report", title: "Report", type: "document", fields: [defineField({ name: "title", type: "string" }), slugField, defineField({ name: "year", type: "number" }), defineField({ name: "file", type: "file" }), defineField({ name: "seo", type: "seo" })] });
export const faq = defineType({ name: "faq", title: "FAQ", type: "document", fields: [defineField({ name: "question", type: "string" }), defineField({ name: "answer", type: "text" }), defineField({ name: "category", type: "string" })] });
export const gallery = defineType({ name: "gallery", title: "Gallery", type: "document", fields: [defineField({ name: "title", type: "string" }), slugField, defineField({ name: "images", type: "array", of: [{ type: "image", options: { hotspot: true }, fields: [{ name: "alt", type: "string" }] }] })] });
export const navigation = defineType({ name: "navigation", title: "Navigation", type: "document", fields: [defineField({ name: "title", type: "string" }), defineField({ name: "items", type: "array", of: [{ type: "link" }] })] });
export const footer = defineType({ name: "footer", title: "Footer", type: "document", fields: [defineField({ name: "title", type: "string" }), defineField({ name: "groups", type: "array", of: [{ type: "object", fields: [defineField({ name: "title", type: "string" }), defineField({ name: "links", type: "array", of: [{ type: "link" }] })] }] })] });
export const globalSettings = defineType({ name: "globalSettings", title: "Global Settings", type: "document", fields: [defineField({ name: "siteName", type: "string" }), defineField({ name: "description", type: "text" }), defineField({ name: "organizationJsonLd", type: "text" }), defineField({ name: "seo", type: "seo" })] });
