import type { HomepageData } from "@/types/cms/homepage";

export const homepageFallback: HomepageData = {
  title: "Project Prometheus",
  seo: { title: "Project Prometheus", description: "A transparent NGO platform for measurable impact, donations, volunteering, and partnerships." },
  hero: { eyebrow: "Transparent NGO impact platform", title: "Every act of care should create measurable change.", description: "Project Prometheus connects donations, volunteering, partnerships, and public reporting into one calm, trustworthy digital home for human progress.", primaryCta: { label: "Donate with confidence", href: "/donate" }, secondaryCta: { label: "Inspect our impact", href: "/impact", variant: "secondary" }, dashboardMetric: { value: 128420, label: "verified acts of support recorded across programs" }, proofPoints: ["Audited reports", "Secure giving", "Partner proof", "Open data"] },
  trust: { eyebrow: "Trust by default", title: "Proof belongs above the fold.", description: "Donors, volunteers, partners, and communities deserve a transparent view into funding, governance, security, and outcomes.", stats: [{ value: "92%", label: "of every unrestricted gift directed to programs", source: "Updated quarterly" }, { value: "48", label: "community partners coordinating local delivery", source: "Verified partner network" }, { value: "18", label: "regions with active impact reporting", source: "Program dashboard" }, { value: "24h", label: "average donor receipt and support response", source: "Support operations" }], highlights: ["Audited annual reporting", "Encrypted donation flows", "Safeguarding policies", "Open methodology"], partners: [{ name: "Civic Data Alliance" }, { name: "Global Volunteer Network" }, { name: "Open Impact Lab" }, { name: "Community Health Fund" }] },
  programs: { eyebrow: "Featured programs", title: "Focused programs. Visible progress.", cta: { label: "View all programs", href: "/programs" }, items: [{ title: "Education access", location: "Learning kits, mentoring, and safe study spaces", progress: 78, href: "/programs/education-access" }, { title: "Community health", location: "Preventive care, local clinics, and family support", progress: 64, href: "/programs/community-health" }, { title: "Climate resilience", location: "Preparedness, clean water, and local adaptation", progress: 52, href: "/programs/climate-resilience" }] },
  impact: { eyebrow: "Impact engine", title: "Measure the work, then publish the evidence.", metrics: [{ label: "People reached", value: 84200 }, { label: "Volunteer hours", value: 31800 }, { label: "Reports published", value: 126 }], mapDescription: "Interactive map module prepared for project locations, outcomes, and regional filters.", timeline: [{ date: "Quarter 1", title: "Local partner onboarding", description: "Field teams validate needs, safeguarding policies, delivery capacity, and reporting cadence before funding begins." }, { date: "Quarter 2", title: "Program delivery", description: "Funds move to approved projects with milestone tracking, procurement checks, and beneficiary-safe communication." }, { date: "Quarter 3", title: "Outcome verification", description: "Impact data is reconciled with partner evidence, site visits, and community feedback loops." }, { date: "Quarter 4", title: "Public reporting", description: "Annual results, financial allocations, methodology notes, and lessons learned are published for public review." }], stories: [{ quote: "The difference was not just the equipment. It was knowing someone would keep showing up until the work was finished.", name: "Amina Rahman", role: "Community program lead" }, { quote: "Prometheus gave our employee volunteers a direct line of sight from time donated to outcomes reported.", name: "Marcus Lee", role: "CSR partner director" }] },
  featuredStory: { eyebrow: "Featured story", quote: "A story of change, not charity.", title: "When support is consistent, communities can plan beyond the emergency.", description: "In one coastal district, local volunteers, health workers, and donors coordinated preparedness kits, clinic access, and transparent reporting before seasonal flooding began.", cta: { label: "Read the story", href: "/stories/coastal-resilience" } },
  donation: { eyebrow: "Donate", title: "Give once, monthly, or toward a verified program.", description: "Every donation flow is designed around clarity: amount, frequency, impact estimate, secure payment, receipt, and transparent follow-up.", securityMessage: "Encrypted payments, donor privacy, instant receipts, and no hidden form steps.", amounts: [25, 50, 100, 250], unitCost: 25 },
  volunteer: { title: "Volunteer with clarity, care, and community.", description: "Find opportunities matched to your skills, schedule, location, and accessibility needs. Track hours, training, events, and certificates from your dashboard.", cta: { label: "Become a volunteer", href: "/volunteer" }, benefits: ["Skill-based roles", "Accessible onboarding", "Community briefings"] },
  news: { eyebrow: "Latest news", title: "Fresh field notes and transparent updates.", featured: { title: "How transparent donation design builds long-term trust", description: "Inside the operating principles behind receipts, reporting, and donor privacy.", href: "/blog/transparent-donation-design" }, items: [{ title: "Quarterly impact notes: what changed across 18 regions", description: "A field-led update on program delivery, data confidence, and next-quarter priorities.", href: "/blog/quarterly-impact-notes" }, { title: "How transparent donation design builds long-term trust", description: "Inside the operating principles behind receipts, reporting, and donor privacy.", href: "/blog/transparent-donation-design" }, { title: "Volunteer teams complete first climate readiness sprint", description: "Community volunteers helped map practical preparedness needs before the monsoon season.", href: "/blog/climate-readiness-sprint" }] },
  testimonials: { eyebrow: "Testimonials", title: "Trusted by people who inspect the work.", items: [{ quote: "The difference was not just the equipment. It was knowing someone would keep showing up until the work was finished.", name: "Amina Rahman", role: "Community program lead" }, { quote: "Prometheus gave our employee volunteers a direct line of sight from time donated to outcomes reported.", name: "Marcus Lee", role: "CSR partner director" }, { quote: "The reporting is unusually clear. I can see what changed, where it changed, and how confident the data is.", name: "Elena Ortiz", role: "Monthly donor" }] },
  footerCta: { eyebrow: "Take action", title: "Support a platform where generosity is emotional, measurable, and transparent.", actions: [{ label: "Donate today", href: "/donate" }, { label: "Contact partnership team", href: "/contact", variant: "secondary" }, { label: "Follow our stories", href: "/stories", variant: "secondary" }], socialLinks: ["LinkedIn", "Instagram", "YouTube", "Press contact"] }
};
