"use client";
import type { ReactNode } from "react";
import { useState } from "react";
import { cn } from "@/utils/cn";

/** Semantic badge for status and metadata. */
export function Badge({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "success" | "warning" | "error" | "info" }) { const tones = { neutral: "bg-muted text-foreground", success: "bg-success/15 text-success", warning: "bg-warning/15 text-warning", error: "bg-error/15 text-error", info: "bg-info/15 text-info" }; return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-semibold", tones[tone])}>{children}</span>; }
/** Accessible avatar with initials fallback. */
export function Avatar({ name, src }: { name: string; src?: string }) { const initials = name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase(); return <span className="inline-grid h-10 w-10 place-items-center overflow-hidden rounded-full bg-muted text-sm font-semibold">{src ? <img src={src} alt={name} className="h-full w-full object-cover" /> : initials}</span>; }
/** Keyboard-friendly tabs using buttons and panels. */
export function Tabs({ tabs }: { tabs: { id: string; label: string; content: ReactNode }[] }) { const [active, setActive] = useState(tabs[0]?.id); return <div><div role="tablist" className="flex flex-wrap gap-2">{tabs.map((tab) => <button key={tab.id} role="tab" aria-selected={active === tab.id} aria-controls={`${tab.id}-panel`} id={`${tab.id}-tab`} onClick={() => setActive(tab.id)} className="min-h-11 rounded-md border px-4 aria-selected:bg-primary aria-selected:text-primary-foreground">{tab.label}</button>)}</div>{tabs.map((tab) => <div key={tab.id} id={`${tab.id}-panel`} role="tabpanel" aria-labelledby={`${tab.id}-tab`} hidden={active !== tab.id} className="mt-4">{tab.content}</div>)}</div>; }
/** Native disclosure accordion. */
export function Accordion({ items }: { items: { title: string; content: ReactNode }[] }) { return <div className="divide-y rounded-xl border bg-surface">{items.map((item) => <details key={item.title} className="group p-4"><summary className="cursor-pointer font-semibold focus-visible:outline-none focus-visible:shadow-focus">{item.title}</summary><div className="mt-3 text-sm leading-6 text-foreground/70">{item.content}</div></details>)}</div>; }
/** Modal built on native dialog semantics with explicit close control. */
export function Modal({ title, trigger, children }: { title: string; trigger: ReactNode; children: ReactNode }) { const [open, setOpen] = useState(false); return <>{<button className="contents" onClick={() => setOpen(true)}>{trigger}</button>}{open ? <div role="dialog" aria-modal="true" aria-labelledby="modal-title" className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="max-w-lg rounded-xl border bg-surface p-6 shadow-card"><h2 id="modal-title" className="font-display text-3xl font-semibold">{title}</h2><div className="mt-4">{children}</div><button className="mt-6 min-h-11 rounded-md bg-primary px-5 font-semibold text-primary-foreground" onClick={() => setOpen(false)}>Close</button></div></div> : null}</>; }
export const Dialog = Modal;
/** Non-interactive tooltip text revealed on hover and focus. */
export function Tooltip({ label, children }: { label: string; children: ReactNode }) { return <span className="group relative inline-flex"><span tabIndex={0}>{children}</span><span role="tooltip" className="pointer-events-none absolute bottom-full left-1/2 mb-2 hidden w-max max-w-72 -translate-x-1/2 rounded-md bg-foreground px-3 py-2 text-xs text-background group-focus-within:block group-hover:block">{label}</span></span>; }
/** Simple dropdown menu with button trigger. */
export function Dropdown({ label, items }: { label: string; items: { label: string; onSelect: () => void }[] }) { const [open, setOpen] = useState(false); return <div className="relative inline-block"><button aria-expanded={open} className="min-h-11 rounded-md border bg-surface px-4" onClick={() => setOpen(!open)}>{label}</button>{open ? <ul className="absolute right-0 z-20 mt-2 min-w-48 rounded-md border bg-surface p-1 shadow-card">{items.map((item) => <li key={item.label}><button className="block w-full rounded px-3 py-2 text-left text-sm hover:bg-muted" onClick={() => { item.onSelect(); setOpen(false); }}>{item.label}</button></li>)}</ul> : null}</div>; }
/** Toast notification region. */
export function Toast({ message, tone = "info" }: { message: string; tone?: "info" | "success" | "error" }) { return <div role="status" className={cn("rounded-lg border bg-surface p-4 shadow-card", tone === "success" && "border-success", tone === "error" && "border-error")}>{message}</div>; }
/** Skeleton loader with reduced-motion-safe pulse. */
export function Skeleton({ className }: { className?: string }) { return <div aria-hidden className={cn("animate-pulse rounded-md bg-muted", className)} />; }
/** Progress indicator. */
export function Progress({ value }: { value: number }) { const safe = Math.min(100, Math.max(0, value)); return <div role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={safe} className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{ width: `${safe}%` }} /></div>; }
/** Pagination navigation. */
export function Pagination({ page, total, onPageChange }: { page: number; total: number; onPageChange: (page: number) => void }) { return <nav aria-label="Pagination" className="flex items-center gap-2"><button className="min-h-11 rounded-md border px-4 disabled:opacity-50" disabled={page <= 1} onClick={() => onPageChange(page - 1)}>Previous</button><span className="text-sm">Page {page} of {total}</span><button className="min-h-11 rounded-md border px-4 disabled:opacity-50" disabled={page >= total} onClick={() => onPageChange(page + 1)}>Next</button></nav>; }
/** Accessible data table. */
export function Table({ caption, columns, rows }: { caption: string; columns: string[]; rows: ReactNode[][] }) { return <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-96 text-left"><caption className="sr-only">{caption}</caption><thead className="bg-muted"><tr>{columns.map((column) => <th key={column} scope="col" className="px-4 py-3 text-sm font-semibold">{column}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex} className="px-4 py-3 text-sm">{cell}</td>)}</tr>)}</tbody></table></div>; }
/** Empty state for no-data and no-result views. */
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <section className="rounded-xl border bg-surface p-8 text-center"><h2 className="font-display text-3xl font-semibold">{title}</h2><p className="mx-auto mt-3 max-w-md text-sm text-foreground/70">{description}</p>{action ? <div className="mt-6">{action}</div> : null}</section>; }
