"use client";
import { useState } from "react";
import { Search } from "lucide-react";

function Field({ label, name, type = "text", required, multiline }: { label: string; name: string; type?: string; required?: boolean; multiline?: boolean }) { return <label className="block text-sm font-medium">{label}{required ? <span aria-hidden="true"> *</span> : null}{multiline ? <textarea name={name} required={required} className="mt-2 min-h-32 w-full rounded-md border bg-background px-4 py-3" /> : <input name={name} type={type} required={required} className="mt-2 min-h-12 w-full rounded-md border bg-background px-4" />}</label>; }
/** Contact form with accessible required fields and status messaging. */
export function ContactForm() { const [sent, setSent] = useState(false); return <form className="grid gap-4 rounded-xl border bg-surface p-6" onSubmit={(event: any) => { event.preventDefault(); setSent(true); }}><Field label="Name" name="name" required /><Field label="Email" name="email" type="email" required /><Field label="Message" name="message" multiline required /><button className="min-h-12 rounded-md bg-primary px-6 font-semibold text-primary-foreground">Send message</button>{sent ? <p role="status" className="text-sm text-success">Message ready to submit.</p> : null}</form>; }
/** Volunteer intake form for opportunity matching. */
export function VolunteerForm() { return <form className="grid gap-4 rounded-xl border bg-surface p-6"><Field label="Full name" name="name" required /><Field label="Email" name="email" type="email" required /><Field label="Skills" name="skills" required /><Field label="Availability" name="availability" required /><button className="min-h-12 rounded-md bg-primary px-6 font-semibold text-primary-foreground">Apply to volunteer</button></form>; }
/** Newsletter signup with consent-aware microcopy. */
export function NewsletterForm() { return <form className="rounded-xl border bg-surface p-6"><label className="text-sm font-medium" htmlFor="newsletter-email">Email address</label><div className="mt-2 flex flex-col gap-3 sm:flex-row"><input id="newsletter-email" type="email" required className="min-h-12 flex-1 rounded-md border bg-background px-4" placeholder="you@example.org" /><button className="min-h-12 rounded-md bg-primary px-6 font-semibold text-primary-foreground">Subscribe</button></div><p className="mt-3 text-xs text-foreground/60">Receive transparent updates. Unsubscribe anytime.</p></form>; }
/** Search input with submit callback and accessible label. */
export function SearchBar({ onSearch, placeholder = "Search" }: { onSearch?: (query: string) => void; placeholder?: string }) { const [query, setQuery] = useState(""); return <form role="search" className="flex gap-2" onSubmit={(event: any) => { event.preventDefault(); onSearch?.(query); }}><label className="sr-only" htmlFor="search-query">Search</label><input id="search-query" value={query} onChange={(event: any) => setQuery(event.currentTarget.value)} className="min-h-12 flex-1 rounded-md border bg-background px-4" placeholder={placeholder} /><button className="inline-flex min-h-12 min-w-12 items-center justify-center rounded-md bg-primary text-primary-foreground"><Search aria-hidden className="h-5 w-5" /><span className="sr-only">Submit search</span></button></form>; }
